// src/web/components/forms/control-password.vue
<template>
  <ControlText
    :label="label"
    type="password"
  />
</template>

<script>
import ControlText from './control-text';

export default {
  name: 'ControlPassword',
  components: { ControlText },
  props: {
    label: {
      type: String,
      default: 'Password'
    }
  }
};
</script>

// client/src/core/components/controls/control-password.tsx
import React from 'react';
import { ControlInput } from './control-input';

interface ControlPasswordProps {
  label: string, 
  value: string,
  setValue: Function
}

function ControlPassword({ label, value, setValue }: ControlPasswordProps) {
  return (
    <ControlInput 
      label={ label } 
      type="password"
      value={ value }
      setValue= { setValue }
    />
  )
}

export { ControlPassword }
