// client/src/modules/users/ui/page-auth.jsx
import React from 'react';
import { spaces } from '__cli/core/design';
import { useIsSignedIn } from '../domain';
import { DialogWelcome } from './dialog-welcome';
import { DialogSign } from './dialog-sign';
import { ContentDisclaimer } from './content-disclaimer';

export const PageAuth = () => {
  const isSignedIn = useIsSignedIn();
  return (
    <div>
      { isSignedIn ? <DialogWelcome /> : <DialogSign /> }
      <ContentDisclaimer css={{ marginTop: spaces.presumptuous }} />
    </div>
  );
};

// web/modules/users/ui/page-auth.vue
<template>
  <div>
    <DialogWelcome v-if="isSignedIn" />
    <DialogSign v-else />
  </div>
</template>

<script>
import { mapGetters } from 'vuex';
import DialogSign from './dialog-sign';
import DialogWelcome from './dialog-welcome';

export default {
  name: 'PageAuth',
  components: { DialogSign, DialogWelcome },
  computed: {
    ...mapGetters('usersStore', ['isSignedIn'])
  }
};
</script>
