// client/src/core/components/controls/control-password.jsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { ControlInput } from './control-input';

function ControlPassword ({ label, ...rest }) {
  const { t } = useTranslation();
  const passwordLabel = label || t('users.password');

  return (
    <ControlInput
      label={passwordLabel}
      type="password"
      { ...rest }
    />
  );
}

export { ControlPassword };

// src/web/components/forms/control-password.vue
<template>
  <ControlText
    :label="label"
    type="password"
  />
</template>

<script>
import ControlText from './control-text';

export default {
  name: 'ControlPassword',
  components: { ControlText },
  props: {
    label: {
      type: String,
      default: 'Password'
    }
  }
};
</script>
