// web/core/components/actions/save-cancel.jsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { spaces } from '@/core/design';
import { ButtonSubmit } from './button-submit';
import { ButtonSecondary } from './button-secondary';

export const SaveCancel = ({ saveLabel, cancelLabel, onCancel }) => {
  const { t } = useTranslation();
  return (
    <>
      <ButtonSecondary
        label={cancelLabel || t('components.cancel')}
        onClick={onCancel}
      />
      <ButtonSubmit
        label={saveLabel || t('components.save')}
        css={{ marginLeft: spaces.normal }}
      />
    </>
  );
};

// client/src/core/components/actions/save-cancel.vue
<template>
  <div>
    <BaseButton
      color="secondary"
      icon="mdi-backspace"
      :text="cancelLabel"
      @click="$emit('cancel')"
    />
    <BaseButton
      color="success"
      icon="mdi-content-save"
      :text="saveLabel"
      @click="$emit('save')"
    />
  </div>
</template>

<script>
import { i18n } from '__cli/core/i18n';

import BaseButton from './base-button';
export default {
  name: 'SaveCancel',
  components: { BaseButton },
  props: {
    cancelLabel: {
      type: String,
      default: i18n.t('actions.cancel')
    },
    saveLabel: {
      type: String,
      default: i18n.t('actions.save')
    }
  }
};
</script>
